services:
  mysql-container:
    image: mysql:latest
    container_name: apoena-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
    volumes:
      - mysql-data-apoena:/var/lib/mysql
    networks:
      - network-apoena
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  client-app:
    build:
      context: ./app
    container_name: apoena-client-app
    environment:
      - DB_HOST=apoena-mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=mydatabase
      - DB_PORT=3306
    depends_on:
      mysql-container:
        condition: service_healthy
    networks:
      - network-apoena

volumes:
  mysql-data-apoena:

networks:
  network-apoena:
    driver: bridge
    name: network-apoena